################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &GA
        Name: GA
        SkipAsForeign: false
        # ID is the key by which this org's MSP definition will be referenced.
        ID: GA
        # MSPDir is the filesystem path which contains the MSP configuration.
        MSPDir: msp 

        Policies: &GAPolicies
            Readers:
                Type: Signature 
                #TODO: thnk about this
                Rule: 
                Writers:
                    Type: Signature
                    Rule:

                Admins:
                    Type: Signature
                    Rule:
                Endorsment:
                    Type: Signature
                    Rule:
                    

        OrdererEndpoints:
        AnchorPeers:
            - Host:
              Port: 


