# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.nalanet.com:
  peer0.ga.nalanet.com:
  peer0.pa.nalanet.com:
  peer0.ta.nalanet.com:

networks:
  nalanet:

services:

  orderer.nalanet.com:
    container_name: orderer.nalanet.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations/ordererOrganizations/nalanet.com/orderers/orderer.nalanet.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/nalanet.com/orderers/orderer.nalanet.com/tls/:/var/hyperledger/orderer/tls
        - orderer.nalanet.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - nalanet

  peer0.ga.nalanet.com:
    container_name: peer0.ga.nalanet.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_nalanet
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.ga.nalanet.com
      - CORE_PEER_ADDRESS=peer0.ga.nalanet.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      -
      - CORE_PEER_CHAINCODEADDRESS=peer0.ga.nalanet.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ga.nalanet.com:7051
      
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ga.nalanet.com:7051
      - CORE_PEER_LOCALMSPID=GAMSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/ga.nalanet.com/peers/peer0.ga.nalanet.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/ga.nalanet.com/peers/peer0.ga.nalanet.com/tls:/etc/hyperledger/fabric/tls
        - peer0.ga.nalanet.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - nalanet

  peer0.pa.nalanet.com:
    container_name: peer0.pa.nalanet.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_nalanet
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.pa.nalanet.com
      - CORE_PEER_ADDRESS=peer0.pa.nalanet.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      -
      - CORE_PEER_CHAINCODEADDRESS=peer0.pa.nalanet.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      -
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pa.nalanet.com:9051
      -
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pa.nalanet.com:9051
      - CORE_PEER_LOCALMSPID=PAMSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/pa.nalanet.com/peers/peer0.pa.nalanet.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/pa.nalanet.com/peers/peer0.pa.nalanet.com/tls:/etc/hyperledger/fabric/tls
        - peer0.pa.nalanet.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
    networks:
      - nalanet

  peer0.ta.nalanet.com:
    container_name: peer0.ta.nalanet.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_nalanet
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.ta.nalanet.com
      - CORE_PEER_ADDRESS=peer0.ta.nalanet.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      -
      - CORE_PEER_CHAINCODEADDRESS=peer0.ta.nalanet.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052

      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ta.nalanet.com:10051
      -
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ta.nalanet.com:10051
      - CORE_PEER_LOCALMSPID=PAMSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/ta.nalanet.com/peers/peer0.ta.nalanet.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/ta.nalanet.com/peers/peer0.ta.nalanet.com/tls:/etc/hyperledger/fabric/tls
        - peer0.ta.nalanet.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 10051:10051
    networks:
      - nalanet
  
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.ga.nalanet.com
      - peer0.pa.nalanet.com
      - peer0.ta.nalanet.com
    networks:
      - nalanet
